apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-post-exporter
  labels:
    app: keycloak-post-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-post-exporter
  template:
    metadata:
      labels:
        app: keycloak-post-exporter
    spec:
      containers:
        - name: exporter
          image: quay.io/thiagobotelho/keycloak-post-exporter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              name: metrics
          envFrom:
            - secretRef:
                name: keycloak-auth-secret
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
