apiVersion: v1
kind: Secret
metadata:
  name: keycloak-auth-secret
  namespace: monitoring
stringData:
  KEYCLOAK_URL: "sua-url-keycloak"
  CLIENT_ID: "seu-client-id"
  CLIENT_SECRET: "seu-client-secret"
